basePath: /
definitions:
  handlers.CostDTO:
    properties:
      filter:
        allOf:
        - $ref: '#/definitions/handlers.FilterDTO'
        description: Filter фильтр использованный для получения результата
      service_count:
        description: |-
          ServiceCount количество всех отфильтрованных подписок
          minimum: 0
          example: 4
        type: integer
      total_cost:
        description: |-
          Cost суммарная стоимость всех отфильтрованных подписок в рублях в месяц, целое число
          minimum: 0
          example: 798
        type: integer
    type: object
  handlers.ErrorDTO:
    properties:
      error:
        description: |-
          Error содержит строку с расшифровкой того что пошло не так
          minLength: 1
          maxLength: 100
          example: subscription not found
        type: string
    type: object
  handlers.FilterDTO:
    properties:
      from:
        description: |-
          From месяц старта подписки
          format: date-time
          example: 07-2025
        type: string
      service_name:
        description: |-
          ServiceName название сервиса подписки
          minLength: 1
          maxLength: 100
          example: Яндекс плюс
        type: string
      to:
        description: |-
          EndDate месяц окончания подписки
          format: date-time
          nullable: true
          example: null
        type: string
      user_id:
        description: |-
          UserUUID UUID пользователя
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
  handlers.SubscriptionFullDTO:
    properties:
      end_date:
        description: |-
          EndDate месяц окончания подписки
          format: date-time
          nullable: true
          example: null
        type: string
      price:
        description: |-
          Price стоимость подписки в рублях в месяц, целое число
          minimum: 1
          example: 399
        type: integer
      service_name:
        description: |-
          ServiceName название сервиса подписки
          minLength: 1
          maxLength: 100
          example: Яндекс плюс
        type: string
      start_date:
        description: |-
          StartDate месяц старта подписки
          format: date-time
          example: 07-2025
        type: string
      user_id:
        description: |-
          UserUUID UUID пользователя
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      uuid:
        description: |-
          UserUUID UUID подписки
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
  handlers.SubscriptionRequestDTO:
    properties:
      end_date:
        description: |-
          EndDate месяц окончания подписки
          format: date-time
          nullable: true
          example: null
        type: string
      price:
        description: |-
          Price стоимость подписки в рублях в месяц, целое число
          minimum: 1
          example: 399
        type: integer
      service_name:
        description: |-
          ServiceName название сервиса подписки
          minLength: 1
          maxLength: 100
          example: Яндекс плюс
        type: string
      start_date:
        description: |-
          StartDate месяц старта подписки
          format: date-time
          example: 07-2025
        type: string
      user_id:
        description: |-
          UserUUID UUID пользователя
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
  handlers.SubscriptionResponceDTO:
    properties:
      end_date:
        description: |-
          EndDate месяц окончания подписки
          format: date-time
          nullable: true
          example: null
        type: string
      price:
        description: |-
          Price стоимость подписки в рублях в месяц, целое число
          minimum: 1
          example: 399
        type: integer
      service_name:
        description: |-
          ServiceName название сервиса подписки
          minLength: 1
          maxLength: 100
          example: Яндекс плюс
        type: string
      start_date:
        description: |-
          StartDate месяц старта подписки
          format: date-time
          example: 07-2025
        type: string
      user_id:
        description: |-
          UserUUID UUID пользователя
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      uuid:
        description: |-
          UserUUID UUID подписки
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: '**REST Сервер для агрегации данных о подписках пользователей на сервисы**'
  title: Тестовое задание
  version: "1.0"
paths:
  /cost:
    get:
      description: |-
        Возвращает информацию о суммарной стоимости и количестве подписок удовлетворяющих фильтрам.

        Также возвращает указанные фильтры
      parameters:
      - default: ""
        description: uuid пользователя для которого будут фильтроваться подписки
        example: '"123e4567-e89b-12d3-a456-426614174000", "10000000-0000-0000-0000-000000000000"'
        in: query
        name: user_uuid
        type: string
      - default: ""
        description: Имя сервиса для которого будут фильтроваться подписки
        example: '"Яндекс плюс"'
        in: query
        name: service_name
        type: string
      - description: С какого месяца фильтруются подписки
        example: '"07-2025"'
        in: query
        name: from
        type: string
      - description: До какого месяца фильтруются подписки
        example: '"07-2025"'
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Все подписки удовлетворяющие фильтрам
          schema:
            $ref: '#/definitions/handlers.CostDTO'
        "400":
          description: Неверный запрос, неверные фильтры, ошибка в формате даты
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Получение информации о стоимости подписок с использованием фильтра
      tags:
      - Стоимость
  /subscriptions:
    get:
      description: Возвращает полную информацию о нескольких подписках, удовлетворяющих
        параметрам фильтрации
      parameters:
      - default: ""
        description: uuid пользователя для которого будут фильтроваться подписки
        example: '"123e4567-e89b-12d3-a456-426614174000", "10000000-0000-0000-0000-000000000000"'
        in: query
        name: user_uuid
        type: string
      - default: ""
        description: Имя сервиса для которого будут фильтроваться подписки
        example: '"Яндекс плюс"'
        in: query
        name: service_name
        type: string
      - description: С какого месяца фильтруются подписки
        example: '"07-2025"'
        in: query
        name: from
        type: string
      - description: До какого месяца фильтруются подписки
        example: '"07-2025"'
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Все подписки удовлетворяющие фильтрам
          schema:
            items:
              $ref: '#/definitions/handlers.SubscriptionResponceDTO'
            type: array
        "400":
          description: Неверный запрос, неверные фильтры, ошибка в формате даты
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Получение информации о подписках с использованием фильтра
      tags:
      - Подписки
    patch:
      consumes:
      - application/json
      description: |
        Изменяет существующую подписку.

        **Входные данные (JSON‑объект `in`):**
        - `uuid` - идентификатор подписки, которую необходимо изменить (обязательный).
        - `user_id` - UUID пользователя (обязательный, не может быть пустым).
        - `service_name` - новое название сервиса (обязательное, не может быть пустым).
        - `price` - новая цена подписки за месяц в рублях (целое неотрицательное число, обязательное).
        - `start_date` - новая дата начала подписки в формате `ММ‑ГГГГ` (например, `07‑2025`). Подписка действует с первого числа указанного месяца (обязательное, не может быть `01‑1970`).
        - `end_date` - новая дата окончания подписки в формате `ММ‑ГГГГ` (необязательное). Если указано, подписка действует до первого числа указанного месяца. Должно быть не ранее `start_date` и не равно `01‑1970`.

        **Логика работы:**
        - Если подписка с указанным `uuid` не найдена - возвращается ошибка.
        - Если пользователь с указанным `in.user_id` не существует - возвращается ошибка.
        - Если сервис с именем `in.service_name` не найден - возвращается ошибка.
        - Все указанные поля заменяют соответствующие значения в существующей подписке.

        **Валидация:**
        - `in.user_id` и `in.service_name` не могут быть пустыми.
        - `in.price` должно быть целым неотрицательным числом.
        - `in.start_date` обязательно, должно соответствовать формату `ММ‑ГГГГ` и не быть `01‑1970`.
        - `in.end_date`, если указано, должно соответствовать формату `ММ‑ГГГГ`, не быть `01‑1970` и не предшествовать `in.start_date`.
      parameters:
      - description: Новые данные для подписки
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/handlers.SubscriptionFullDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Созданная подписка
          schema:
            $ref: '#/definitions/handlers.SubscriptionResponceDTO'
        "400":
          description: Неверный запрос, ошибка во входящем json, ошибка валидации
            json
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "404":
          description: Не найдена подписка с указанным in.uuid
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Изменение подписки
      tags:
      - Подписки
    post:
      consumes:
      - application/json
      description: |-
        Создает подписку для пользователя.

        **Параметры:**
        - `user_id` - UUID пользователя (обязательный).
        - `service_name` - название сервиса (обязательное).
        - `price` - цена подписки за месяц в рублях (целое неотрицательное число, обязательное).
        - `start_date` - дата начала подписки в формате `ММ‑ГГГГ` (например, `07‑2025`). Подписка действует с первого числа указанного месяца (обязательное, не может быть `01‑1970`).
        - `end_date` - дата окончания подписки в формате `ММ‑ГГГГ` (необязательное). Если указано, подписка действует до первого числа указанного месяца. Должно быть не ранее `start_date` и не равно `01‑1970`.

        **Логика работы:**
        - Если пользователь с указанным `user_id` не существует - возвращается ошибка.
        - Если сервис с именем `service_name` не найден - возвращается ошибка.
        - Если `end_date` не указано, подписка действует 30 дней.

        **Валидация:**
        - `user_id` и `service_name` не могут быть пустыми.
        - `price` должно быть целым неотрицательным числом.
        - `start_date` обязательно, должно соответствовать формату `ММ‑ГГГГ` и не быть `01‑1970`.
        - `end_date`, если указано, должно соответствовать формату `ММ‑ГГГГ`, не быть `01‑1970` и не предшествовать `start_date`.
      parameters:
      - description: Данные новой подписки
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/handlers.SubscriptionRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Созданная подписка
          schema:
            $ref: '#/definitions/handlers.SubscriptionResponceDTO'
        "400":
          description: Неверный запрос, ошибка во входящем json, ошибка валидации
            json
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "404":
          description: Не найден пользователем с указанным user_id или сервис с именем
            service_name
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "409":
          description: У пользователя уже существует подписка на сервис и время действия
            подписок пересекается
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Создание новой подписки
      tags:
      - Подписки
  /subscriptions/{uuid}:
    delete:
      description: |-
        Удаляет существующую подписку с указанным `uuid`.

        Если подписки с таким `uuid` не существует, ничего не делает, возвращает информацию о ошибке.
      parameters:
      - description: UUID подписки
        example: '"123e4567-e89b-12d3-a456-426614174000", "10000000-0000-0000-0000-000000000000"'
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Подписка удалена
        "400":
          description: Неверный запрос, пустой uuid
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "404":
          description: Не найдена подписка с указанным uuid
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Удаление подписки
      tags:
      - Подписки
    get:
      description: Возвращает полную информацию об одной подписке, по предоставленному
        `uuid`
      parameters:
      - description: UUID подписки
        example: '"123e4567-e89b-12d3-a456-426614174000", "10000000-0000-0000-0000-000000000000"'
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Найденная подписка пользователя
          schema:
            $ref: '#/definitions/handlers.SubscriptionResponceDTO'
        "400":
          description: Неверный запрос, пустой uuid
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "404":
          description: Подписка с таким uuid не найдена
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
        "500":
          description: Внутренняя ошибка работы сервера
          schema:
            $ref: '#/definitions/handlers.ErrorDTO'
      summary: Получение информации о подписке по UUID
      tags:
      - Подписки
schemes:
- http
swagger: "2.0"
